hotkey-context =
    .player = Игрок
    .spectator = Зритель
    .chat-input = Ввод чата
    .menu = Меню
    .editor = Редактор

## chat.yaml
hotkey-description-openteamchat = Открыть чат команды
hotkey-description-opengeneralchat = Открыть общий чат
hotkey-description-togglechatmode = Сменить режим чата
hotkey-description-autocomplete = Автодополнение

## control-groups.yaml
hotkey-description-controlgroupselect01 = Выбрать группу 1
hotkey-description-controlgroupselect02 = Выбрать группу 2
hotkey-description-controlgroupselect03 = Выбрать группу 3
hotkey-description-controlgroupselect04 = Выбрать группу 4
hotkey-description-controlgroupselect05 = Выбрать группу 5
hotkey-description-controlgroupselect06 = Выбрать группу 6
hotkey-description-controlgroupselect07 = Выбрать группу 7
hotkey-description-controlgroupselect08 = Выбрать группу 8
hotkey-description-controlgroupselect09 = Выбрать группу 9
hotkey-description-controlgroupselect10 = Выбрать группу 0
hotkey-description-controlgroupcreate01 = Создать группу 1
hotkey-description-controlgroupcreate02 = Создать группу 2
hotkey-description-controlgroupcreate03 = Создать группу 3
hotkey-description-controlgroupcreate04 = Создать группу 4
hotkey-description-controlgroupcreate05 = Создать группу 5
hotkey-description-controlgroupcreate06 = Создать группу 6
hotkey-description-controlgroupcreate07 = Создать группу 7
hotkey-description-controlgroupcreate08 = Создать группу 8
hotkey-description-controlgroupcreate09 = Создать группу 9
hotkey-description-controlgroupcreate10 = Создать группу 0
hotkey-description-controlgroupaddto01 = Добавить в группу 1
hotkey-description-controlgroupaddto02 = Добавить в группу 2
hotkey-description-controlgroupaddto03 = Добавить в группу 3
hotkey-description-controlgroupaddto04 = Добавить в группу 4
hotkey-description-controlgroupaddto05 = Добавить в группу 5
hotkey-description-controlgroupaddto06 = Добавить в группу 6
hotkey-description-controlgroupaddto07 = Добавить в группу 7
hotkey-description-controlgroupaddto08 = Добавить в группу 8
hotkey-description-controlgroupaddto09 = Добавить в группу 9
hotkey-description-controlgroupaddto10 = Добавить в группу 0
hotkey-description-controlgroupcombinewith01 = Объединить с группой 1
hotkey-description-controlgroupcombinewith02 = Объединить с группой 2
hotkey-description-controlgroupcombinewith03 = Объединить с группой 3
hotkey-description-controlgroupcombinewith04 = Объединить с группой 4
hotkey-description-controlgroupcombinewith05 = Объединить с группой 5
hotkey-description-controlgroupcombinewith06 = Объединить с группой 6
hotkey-description-controlgroupcombinewith07 = Объединить с группой 7
hotkey-description-controlgroupcombinewith08 = Объединить с группой 8
hotkey-description-controlgroupcombinewith09 = Объединить с группой 9
hotkey-description-controlgroupcombinewith10 = Объединить с группой 0
hotkey-description-controlgroupjumpto01 = Перейти к группе 1
hotkey-description-controlgroupjumpto02 = Перейти к группе 2
hotkey-description-controlgroupjumpto03 = Перейти к группе 3
hotkey-description-controlgroupjumpto04 = Перейти к группе 4
hotkey-description-controlgroupjumpto05 = Перейти к группе 5
hotkey-description-controlgroupjumpto06 = Перейти к группе 6
hotkey-description-controlgroupjumpto07 = Перейти к группе 7
hotkey-description-controlgroupjumpto08 = Перейти к группе 8
hotkey-description-controlgroupjumpto09 = Перейти к группе 9
hotkey-description-controlgroupjumpto10 = Перейти к группе 0
hotkey-description-removefromcontrolgroup = Убрать из группы

## editor.yaml
hotkey-description-editorundo = Отменить
hotkey-description-editorredo = Повторить
hotkey-description-editorcopy = Копировать
hotkey-description-editorquicksave = Сохранить карту
hotkey-description-editorpaste = Вставить
hotkey-description-editordeleteselection = Удалить выбранное
hotkey-description-editorselecttab = Выбрать вкладку
hotkey-description-editortilestab = Вкладка тайлов
hotkey-description-editoroverlaystab = Вкладка слоёв
hotkey-description-editoractorstab = Вкладка объектов
hotkey-description-editortoolstab = Вкладка инструментов
hotkey-description-editorhistorytab = Вкладка истории
hotkey-description-editorsettingstab = Вкладка настроек
hotkey-description-editortogglegridoverlay = Сетка
hotkey-description-editortogglebuildableoverlay = Слой застройки
hotkey-description-editortogglemarkeroverlay = Слой маркеров

## game.yaml
hotkey-description-cyclebase = К базе
hotkey-description-tolastevent = К последнему сигналу радара
hotkey-description-toselection = К выбранному
hotkey-description-selectallunits = Выбрать все боевые юниты
hotkey-description-selectunitsbytype = Выбрать юниты по типу
hotkey-description-cycleharvesters = Листать сборщики
hotkey-description-pause = Пауза / Продолжить
hotkey-description-sell = Режим продажи
hotkey-description-repair = Режим ремонта
hotkey-description-placebeacon = Поставить маяк
hotkey-description-cyclestatusbars = Вид полос состояния
hotkey-description-togglemute = Вкл./выкл. звук
hotkey-description-toggleplayerstancecolor = Цвета отношений
hotkey-description-takescreenshot = Сделать скриншот
hotkey-description-attackmove = Движение с атакой
hotkey-description-stop = Стоп
hotkey-description-scatter = Рассредоточиться
hotkey-description-deploy = Развернуть
hotkey-description-guard = Охранять
hotkey-description-stanceattackanything = Атаковать всё
hotkey-description-stancedefend = Оборона
hotkey-description-stancereturnfire = Ответный огонь
hotkey-description-stanceholdfire = Не стрелять
hotkey-description-stopmusic = Стоп
hotkey-description-pausemusic = Пауза/продолжить
hotkey-description-prevmusic = Предыдущий
hotkey-description-nextmusic = Следующий

## observer.yaml
hotkey-description-observercombinedview = Все игроки
hotkey-description-observerworldview = Отключить туман
hotkey-description-replayspeedslow = Медленно
hotkey-description-replayspeedregular = Обычно
hotkey-description-replayspeedfast = Быстро
hotkey-description-replayspeedmax = Максимум
hotkey-description-statisticsnone = Без статистики
hotkey-description-statisticsbasic = Базовая статистика
hotkey-description-statisticseconomy = Экономика
hotkey-description-statisticsproduction = Производство
hotkey-description-statisticssupportpowers = Спецспособности
hotkey-description-statisticscombat = Бой
hotkey-description-statisticsarmy = Армия
hotkey-description-statisticsgraph = График статистики
hotkey-description-statisticsarmygraph = График армии

## production-common.yaml
hotkey-description-cycleproductionbuildings = Следующее здание
hotkey-description-selectproductionbuilding = Текущее здание
hotkey-description-production01 = Ячейка 01
hotkey-description-production02 = Ячейка 02
hotkey-description-production03 = Ячейка 03
hotkey-description-production04 = Ячейка 04
hotkey-description-production05 = Ячейка 05
hotkey-description-production06 = Ячейка 06
hotkey-description-production07 = Ячейка 07
hotkey-description-production08 = Ячейка 08
hotkey-description-production09 = Ячейка 09
hotkey-description-production10 = Ячейка 10
hotkey-description-production11 = Ячейка 11
hotkey-description-production12 = Ячейка 12
hotkey-description-production13 = Ячейка 13
hotkey-description-production14 = Ячейка 14
hotkey-description-production15 = Ячейка 15
hotkey-description-production16 = Ячейка 16
hotkey-description-production17 = Ячейка 17
hotkey-description-production18 = Ячейка 18
hotkey-description-production19 = Ячейка 19
hotkey-description-production20 = Ячейка 20
hotkey-description-production21 = Ячейка 21
hotkey-description-production22 = Ячейка 22
hotkey-description-production23 = Ячейка 23
hotkey-description-production24 = Ячейка 24

## supportpowers.yaml
hotkey-description-supportpower01 = Ячейка 01
hotkey-description-supportpower02 = Ячейка 02
hotkey-description-supportpower03 = Ячейка 03
hotkey-description-supportpower04 = Ячейка 04
hotkey-description-supportpower05 = Ячейка 05
hotkey-description-supportpower06 = Ячейка 06

## viewport.yaml
hotkey-description-mapscrollup = Прокрутка вверх
hotkey-description-mapscrolldown = Прокрутка вниз
hotkey-description-mapscrollleft = Прокрутка влево
hotkey-description-mapscrollright = Прокрутка вправо
hotkey-description-mapjumptotopedge = К верхнему краю
hotkey-description-mapjumptobottomedge = К нижнему краю
hotkey-description-mapjumptoleftedge = К левому краю
hotkey-description-mapjumptorightedge = К правому краю
hotkey-description-mapbookmarksave01 = Записать закладку 1
hotkey-description-mapbookmarkrestore01 = К закладке 1
hotkey-description-mapbookmarksave02 = Записать закладку 2
hotkey-description-mapbookmarkrestore02 = К закладке 2
hotkey-description-mapbookmarksave03 = Записать закладку 3
hotkey-description-mapbookmarkrestore03 = К закладке 3
hotkey-description-mapbookmarksave04 = Записать закладку 4
hotkey-description-mapbookmarkrestore04 = К закладке 4
hotkey-description-zoomin = Приблизить
hotkey-description-zoomout = Отдалить
hotkey-description-resetzoom = Сбросить масштаб
