Container@INPUT_PANEL:
	Logic: InputSettingsLogic
	Width: PARENT_RIGHT
	Height: PARENT_BOTTOM
	Children:
		ScrollPanel@SETTINGS_SCROLLPANEL:
			Width: PARENT_RIGHT
			Height: PARENT_BOTTOM
			CollapseHiddenChildren: True
			TopBottomSpacing: 5
			ItemSpacing: 10
			Children:
				Background@SECTION_HEADER:
					X: 5
					Width: PARENT_RIGHT - 24 - 10
					Height: 13
					Background: separator
					ClickThrough: True
					Children:
						Label@LABEL:
							Width: PARENT_RIGHT
							Height: PARENT_BOTTOM
							Font: TinyBold
							Align: Center
							Text: Ввод
				Container@ROW:
					Width: PARENT_RIGHT - 24
					Height: 50
					Children:
						Container@MOUSE_CONTROL_CONTAINER:
							X: 10
							Width: PARENT_RIGHT / 2 - 20
							Children:
								Label@MOUSE_CONTROL_LABEL:
									Width: PARENT_RIGHT
									Height: 20
									Font: Regular
									Text: Схема управления:
								DropDownButton@MOUSE_CONTROL_DROPDOWN:
									Y: 25
									Width: PARENT_RIGHT
									Height: 25
									Font: Regular
						Container@ZOOM_MODIFIER_CONTAINER:
							X: PARENT_RIGHT / 2 + 10
							Width: PARENT_RIGHT / 2 - 20
							Children:
								Label@ZOOM_MODIFIER_LABEL:
									Width: PARENT_RIGHT
									Height: 20
									Font: Regular
									Text: Модификатор приближения:
								DropDownButton@ZOOM_MODIFIER:
									Y: 25
									Width: PARENT_RIGHT
									Height: 25
									Font: Regular
						Container@MOUSE_CONTROL_DESC_CLASSIC:
							X: 10
							Y: 55
							Width: PARENT_RIGHT
							Children:
								LabelWithHighlight@DESC_SELECTION:
									Height: 16
									Font: Small
									Text: - Выберите юнитов, используя {ЛКМ}
								LabelWithHighlight@DESC_COMMANDS:
									Y: 17
									Height: 16
									Font: Small
									Text: - Командуйте юнитами, используя {ЛКМ} 
								LabelWithHighlight@DESC_BUILDIGS:
									Y: 34
									Height: 16
									Font: Small
									Text: - Размещайте здания, используя {ЛКМ} 
								LabelWithHighlight@DESC_SUPPORT:
									Y: 51
									Height: 16
									Font: Small
									Text: - Вызывайте поддержку, используя {ЛКМ} 
								LabelWithHighlight@DESC_ZOOM:
									Y: 68
									Height: 16
									Font: Small
									Text: - Приближайте камеру, используя {Колёсико}
								LabelWithHighlight@DESC_ZOOM_MODIFIER:
									Y: 68
									Height: 16
									Font: Small
									Text: - Приближайте камеру, используя {MODIFIER + Колёсико}
								LabelWithHighlight@DESC_SCROLL_RIGHT:
									Y: 85
									Height: 16
									Font: Small
									Text: - Передвигайте камеру, используя {ПКМ} 
								LabelWithHighlight@DESC_SCROLL_MIDDLE:
									Y: 85
									Height: 16
									Font: Small
									Text: - Передвигайте камеру, используя {СКМ}
								Label@DESC_EDGESCROLL:
									X: 9
									Y: 102
									Height: 16
									Font: Small
									Text: или перемещая курсор на край экрана
						Container@MOUSE_CONTROL_DESC_MODERN:
							X: 10
							Y: 55
							Width: PARENT_RIGHT / 2 - 20
							Children:
								LabelWithHighlight@DESC_SELECTION:
									Height: 16
									Font: Small
									Text: - Выберите юнитов, используя {ЛКМ} 
								LabelWithHighlight@DESC_COMMANDS:
									Y: 17
									Height: 16
									Font: Small
									Text: - Командуйте юнитами, используя {ПКМ} 
								LabelWithHighlight@DESC_BUILDIGS:
									Y: 34
									Height: 16
									Font: Small
									Text: - Размещайте здания, используя {ЛКМ} 
								LabelWithHighlight@DESC_SUPPORT:
									Y: 51
									Height: 16
									Font: Small
									Text: - Вызывайте поддержку, используя {ЛКМ} 
								LabelWithHighlight@DESC_ZOOM:
									Y: 68
									Height: 16
									Font: Small
									Text: - Приближайте камеру, используя {Колёсико}
								LabelWithHighlight@DESC_ZOOM_MODIFIER:
									Y: 68
									Height: 16
									Font: Small
									Text: - Приближайте камеру, используя {MODIFIER + Колёсико}
								LabelWithHighlight@DESC_SCROLL_RIGHT:
									Y: 85
									Height: 16
									Font: Small
									Text: - Передвигайте камеру, используя {ПКМ} 
								LabelWithHighlight@DESC_SCROLL_MIDDLE:
									Y: 85
									Height: 16
									Font: Small
									Text: - Передвигайте камеру, используя {СКМ} 
								Label@DESC_EDGESCROLL:
									X: 9
									Y: 102
									Height: 16
									Font: Small
									Text: или перемещая курсор на край экрана
				Container@ROW:
					Width: PARENT_RIGHT - 24
					Height: 20
					Children:
						Container@EDGESCROLL_CHECKBOX_CONTAINER:
							X: PARENT_RIGHT / 2 + 10
							Width: PARENT_RIGHT / 2 - 20
							Children:
								Checkbox@EDGESCROLL_CHECKBOX:
									Width: PARENT_RIGHT
									Height: 20
									Font: Regular
									Text: Край экрана двигает камеру
				Container@ROW:
					Width: PARENT_RIGHT - 24
					Height: 20
					Children:
						Container@ALTERNATE_SCROLL_CHECKBOX_CONTAINER:
							X: PARENT_RIGHT / 2 + 10
							Width: PARENT_RIGHT / 2 - 20
							Children:
								Checkbox@ALTERNATE_SCROLL_CHECKBOX:
									Width: PARENT_RIGHT
									Height: 20
									Font: Regular
									Text: Alternate Mouse Panning
				Container@ROW:
					Width: PARENT_RIGHT - 24
					Height: 20
					Children:
						Container@LOCKMOUSE_CHECKBOX_CONTAINER:
							X: PARENT_RIGHT / 2 + 10
							Width: PARENT_RIGHT / 2 - 20
							Children:
								Checkbox@LOCKMOUSE_CHECKBOX:
									Width: PARENT_RIGHT
									Height: 20
									Font: Regular
									Text: Заблокировать мышь окном
				Container@SPACER:
					Height: 30
				Container@ROW:
					Width: PARENT_RIGHT - 24
					Height: 50
					Children:
						Container@MOUSE_SCROLL_TYPE_CONTAINER:
							X: 10
							Width: PARENT_RIGHT / 2 - 20
							Children:
								Label@MOUSE_SCROLL_TYPE_LABEL:
									Width: PARENT_RIGHT
									Height: 20
									Font: Regular
									Text: Pan Behaviour:
								DropDownButton@MOUSE_SCROLL_TYPE_DROPDOWN:
									Y: 25
									Width: PARENT_RIGHT
									Height: 25
									Font: Regular
						Container@SCROLLSPEED_SLIDER_CONTAINER:
							X: PARENT_RIGHT / 2 + 10
							Width: PARENT_RIGHT / 2 - 20
							Children:
								Label@SCROLL_SPEED_LABEL:
									Width: PARENT_RIGHT
									Height: 20
									Text: Pan Speed:
								Slider@SCROLLSPEED_SLIDER:
									Y: 25
									Width: PARENT_RIGHT
									Height: 20
									Ticks: 7
									MinimumValue: 10
									MaximumValue: 50
				Container@ROW:
					Width: PARENT_RIGHT - 24
					Height: 50
					Children:
						Container@ZOOMSPEED_SLIDER_CONTAINER:
							X: PARENT_RIGHT / 2 + 10
							Width: PARENT_RIGHT / 2 - 20
							Children:
								Label@ZOOM_SPEED_LABEL:
									Width: PARENT_RIGHT
									Height: 20
									Text: Zoom Speed:
								ExponentialSlider@ZOOMSPEED_SLIDER:
									Y: 25
									Width: PARENT_RIGHT
									Height: 20
									Ticks: 7
									MinimumValue: 0.01
									MaximumValue: 0.4
				Container@ROW:
					Width: PARENT_RIGHT - 24
					Height: 50
					Children:
						Container@UI_SCROLLSPEED_SLIDER_CONTAINER:
							X: PARENT_RIGHT / 2 + 10
							Width: PARENT_RIGHT / 2 - 20
							Children:
								Label@UI_SCROLL_SPEED_LABEL:
									Width: PARENT_RIGHT
									Height: 20
									Text: UI Scroll Speed:
								Slider@UI_SCROLLSPEED_SLIDER:
									Y: 25
									Width: PARENT_RIGHT
									Height: 20
									Ticks: 7
									MinimumValue: 1
									MaximumValue: 100
